name: Docker
on: [ push ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: build
        run: | 
          npm i
          npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            .
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Build dockerfile
        run: docker build -t rius/wave.music.front
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push to registry
        run: docker push rius/wave.music.front
