name: Docker
on:
  pull_request:
  push:
    branches:
      - main
      - WV-61

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: build
        run: | 
          npm i
          npm run build
      - name: Build dockerfile
        run: |
          docker build . -t rius/wave.music.front
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push rius/wave.music.front

